site_name: STROOP
nav:
  - Home: index.md
  - User Guide:
    - Getting Started: getting-started.md
    - Tabs: 
      - Understanding Tabs: tabs.md
      - Specific Tabs:
        - Object Tab: tabs/object.md